# Generated by Django 2.2.11 on 2020-03-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapstore2_adapter', '0002_auto_20190618_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapstoreattribute',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('binary', 'Binary')], max_length=80),
        ),
    ]
