# Generated by Django 2.2.16 on 2021-02-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapstore2_adapter', '0003_auto_20200310_0848'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mapstoreattribute',
            table='mapstore2_adapter_mapstoreattribute',
        ),
        migrations.AlterModelTable(
            name='mapstoredata',
            table='mapstore2_adapter_mapstoredata',
        ),
        migrations.AlterModelTable(
            name='mapstoreresource',
            table='mapstore2_adapter_mapstoreresource',
        ),
    ]
