# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 08:20


from django.db import migrations

import logging
logger = logging.getLogger(__name__)
   
SQL_MIGRATION = '''WITH mapstore_blob AS (
    SELECT
        msd.resource_id, msd.blob
    FROM
        public.mapstore2_adapter_mapstoredata msd
    JOIN public.maps_map md 
    ON msd.resource_id =md.resourcebase_ptr_id)
UPDATE base_resourcebase
SET "blob"=subquery."blob"
FROM (select resource_id,"blob" from mapstore_blob gg) AS subquery
WHERE base_resourcebase.id=subquery.resource_id;
'''

class Migration(migrations.Migration):

    dependencies = [
        ('mapstore2_adapter', '0004_auto_20210219_1015'),
        ('maps', '0030_auto_20210506_0836')
    ]

    operations = [
        migrations.RunSQL(SQL_MIGRATION)
    ]
