# Generated by Django 3.2.4 on 2021-07-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geoapps', '0004_merge_0003_alter_geoapp_name_0003_update_detail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('geoapp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geoapps.geoapp')),
                ('url', models.CharField(max_length=1200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('geoapps.geoapp',),
        ),
    ]
