# Generated by Django 2.2.15 on 2020-10-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geoapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoStory',
            fields=[
                ('geoapp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geoapps.GeoApp')),
                ('_app_type', models.CharField(default='GeoStory', max_length=255, verbose_name='Apps Type')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('geoapps.geoapp',),
        ),
    ]
