# Generated by Django 2.2.15 on 2020-10-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp_geostories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geostory',
            name='_app_type',
        ),
        migrations.AddField(
            model_name='geostory',
            name='app_type',
            field=models.CharField(db_column='geostory_app_type', default='GeoStory', max_length=255, verbose_name='Apps Type'),
        ),
    ]
